{{- include "bjw-s.common.loader.init" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-authentication-reader
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
    namespace: {{ .Release.Namespace }}
