---
apiVersion: v2
version: 3.0.0
description: Creates ingress reverse-proxies for external hosts with minimum boilerplate
name: reverse-proxy
appVersion: 1.2.0
kubeVersion: ">=1.16.0-0"
keywords:
  - reverse-proxy
  - ingress
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/reverse-proxy
icon: https://kubernetes.io/images/wheel.svg
sources:
  - https://kubernetes.io/docs/concepts/services-networking/ingress/
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        **BREAKING**: Updated library version to 1.0.1.
      links:
        - name: Common library chart definition
          url: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml
