---
postgres-operator:
  enabled: true
  configMajorVersionUpgrade:
    # "off": no upgrade, "manual": manifest triggers action, "full": minimal version violation triggers too
    major_version_upgrade_mode: full
  configKubernetes:
    # enable_pod_antiaffinity: true
    enable_cross_namespace_secret: false
    # pod_environment_configmap: "postgres-pod-config"
    watched_namespace: "*"
    # list of labels that can be inherited from the cluster manifest
    inherited_labels:
      - application
      - environment
    # Disable PDB since they prevent the drain
    # https://github.com/zalando/postgres-operator/issues/547
    enable_pod_disruption_budget: false
    enable_owner_references: true
  # configure resource requests for the Postgres pods
  configPostgresPodResources:
    # CPU limits for the postgres containers
    default_cpu_limit: "2"
    # memory limits for the postgres containers
    default_memory_limit: 2000Mi

postgres: {}

persistentVolumes:
  replicaNodes:
    - dummy

dumpBackup:
  enabled: true
  type: emptyDir
  subpath: "."
  schedule: "@daily"
