---
apiVersion: v2
appVersion: latest
description: Multiplexer for lorawan gateway packages
name: chirpstack-packet-multiplexer
version: 2.1.0
keywords:
  - lorawan
  - chirpstack
home: https://github.com/angelnu/helm-charts/tree/main/charts/apps/chirpstack-packet-multiplexer
icon: https://www.chirpstack.io/static/logo.png
sources:
  - https://github.com/angelnu/chirpstack-packet-multiplexer
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.2

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        Include persistency
        Dissable probes
